apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: app
  labels:
    app: app
spec:
  selector:
    matchLabels:
      app: app
  namespaceSelector:
    matchNames:
    - app
  endpoints:
  - port: metrics
    path: '/metrics'
