apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: paymentservice
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: paymentservice
    spec:
      containers:
      - name: server
        image: evgeniim/boutique-paymentservice:0.0.2
        ports:
        - containerPort: 50051
        env:
        - name: PORT
          value: "50051"
