apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: frontend
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-production"
spec:
  tls:
  - hosts:
    - frontend.35.228.150.27.nip.io
    secretName: frontend.35.228.150.27.nip.io
  rules:
  - host: frontend.35.228.150.27.nip.io
    http:
      paths:
      - path: /
        backend:
          serviceName: frontend
          servicePort: {{ .Values.service.port }}